alter table public.profiles
add column if not exists theme_preset text not null default 'mint';

alter table public.links
add column if not exists link_style text not null default 'default';
alter table public.links
add column if not exists starts_at timestamptz;
alter table public.links
add column if not exists ends_at timestamptz;

create table if not exists public.page_views (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  viewed_at timestamptz not null default now()
);

create table if not exists public.link_clicks (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  link_id uuid,
  clicked_at timestamptz not null default now()
);

alter table public.page_views enable row level security;
alter table public.link_clicks enable row level security;

drop policy if exists "Qualquer visitante registra visualização" on public.page_views;
drop policy if exists "Usuário consulta suas visualizações" on public.page_views;
drop policy if exists "Qualquer visitante registra clique" on public.link_clicks;
drop policy if exists "Usuário consulta seus cliques" on public.link_clicks;

create policy "Qualquer visitante registra visualização"
on public.page_views for insert with check (true);
create policy "Usuário consulta suas visualizações"
on public.page_views for select using (auth.uid() = profile_id);
create policy "Qualquer visitante registra clique"
on public.link_clicks for insert with check (true);
create policy "Usuário consulta seus cliques"
on public.link_clicks for select using (auth.uid() = profile_id);

create index if not exists page_views_profile_date_idx
on public.page_views(profile_id, viewed_at desc);
create index if not exists link_clicks_profile_date_idx
on public.link_clicks(profile_id, clicked_at desc);
