create table if not exists public.page_reports (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  reporter_id uuid references auth.users(id) on delete set null,
  reported_username text not null,
  reason text not null,
  details text not null default '',
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

alter table public.page_reports enable row level security;

drop policy if exists "Visitantes enviam denuncias" on public.page_reports;
create policy "Visitantes enviam denuncias"
on public.page_reports for insert with check (true);

create index if not exists page_reports_status_date_idx
on public.page_reports(status, created_at desc);
