create extension if not exists "pgcrypto";

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null check (username ~ '^[a-z0-9_]{3,30}$'),
  display_name text not null default '',
  bio text not null default '',
  role text not null default '',
  location text not null default '',
  avatar_url text not null default '',
  banner_url text not null default '',
  instagram_handle text not null default '',
  show_bio boolean not null default true,
  show_role boolean not null default true,
  show_location boolean not null default false,
  accent_color text not null default '#6ef5a8',
  background_color text not null default '#0b0d11',
  background_secondary text not null default '#17231d',
  background_style text not null default 'theme',
  font_family text not null default 'modern',
  button_radius integer not null default 18,
  theme_preset text not null default 'mint',
  theme text not null default 'system' check (theme in ('system', 'dark', 'light')),
  updated_at timestamptz not null default now()
);

create table if not exists public.links (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  description text not null default '',
  url text not null check (url ~ '^https?://'),
  position integer not null default 0,
  is_featured boolean not null default false,
  is_visible boolean not null default true,
  link_style text not null default 'default',
  starts_at timestamptz,
  ends_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.links enable row level security;

create policy "Perfis públicos podem ser vistos" on public.profiles for select using (true);
create policy "Usuário cria o próprio perfil" on public.profiles for insert with check (auth.uid() = id);
create policy "Usuário edita o próprio perfil" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);
create policy "Links visíveis são públicos" on public.links for select using (is_visible or auth.uid() = profile_id);
create policy "Usuário cria os próprios links" on public.links for insert with check (auth.uid() = profile_id);
create policy "Usuário edita os próprios links" on public.links for update using (auth.uid() = profile_id) with check (auth.uid() = profile_id);
create policy "Usuário exclui os próprios links" on public.links for delete using (auth.uid() = profile_id);

create index if not exists links_profile_position_idx on public.links(profile_id, position);

create table if not exists public.page_views (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  viewed_at timestamptz not null default now()
);

create table if not exists public.link_clicks (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  link_id uuid,
  link_title text,
  link_url text,
  clicked_at timestamptz not null default now()
);

alter table public.page_views enable row level security;
alter table public.link_clicks enable row level security;

create policy "Qualquer visitante registra visualização"
on public.page_views for insert with check (true);
create policy "Usuário consulta suas visualizações"
on public.page_views for select using (auth.uid() = profile_id);
create policy "Qualquer visitante registra clique"
on public.link_clicks for insert with check (true);
create policy "Usuário consulta seus cliques"
on public.link_clicks for select using (auth.uid() = profile_id);

create index if not exists page_views_profile_date_idx
on public.page_views(profile_id, viewed_at desc);
create index if not exists link_clicks_profile_date_idx
on public.link_clicks(profile_id, clicked_at desc);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'profile-media',
  'profile-media',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy "Imagens de perfil são públicas"
on storage.objects for select
using (bucket_id = 'profile-media');

create policy "Usuário envia suas imagens"
on storage.objects for insert to authenticated
with check (
  bucket_id = 'profile-media'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "Usuário atualiza suas imagens"
on storage.objects for update to authenticated
using (
  bucket_id = 'profile-media'
  and (storage.foldername(name))[1] = auth.uid()::text
)
with check (
  bucket_id = 'profile-media'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "Usuário exclui suas imagens"
on storage.objects for delete to authenticated
using (
  bucket_id = 'profile-media'
  and (storage.foldername(name))[1] = auth.uid()::text
);
